#pragma once

constexpr const int RK_KEY_UNKNOWN					= - 1;
constexpr const int RK_KEY_SPACE					= 32;
constexpr const int RK_KEY_APOSTROPHE				= 39; /* ' */
constexpr const int RK_KEY_COMMA					= 44; /* , */
constexpr const int RK_KEY_MINUS					= 45; /* - */
constexpr const int RK_KEY_PERIOD					= 46; /* . */
constexpr const int RK_KEY_SLASH					= 47; /* / */
constexpr const int RK_KEY_0						= 48;
constexpr const int RK_KEY_1						= 49;
constexpr const int RK_KEY_2						= 50;
constexpr const int RK_KEY_3						= 51;
constexpr const int RK_KEY_4						= 52;
constexpr const int RK_KEY_5						= 53;
constexpr const int RK_KEY_6						= 54;
constexpr const int RK_KEY_7						= 55;
constexpr const int RK_KEY_8						= 56;
constexpr const int RK_KEY_9						= 57;
constexpr const int RK_KEY_SEMICOLON				= 59; /* ; */
constexpr const int RK_KEY_EQUAL					= 61; /* = */
constexpr const int RK_KEY_A						= 65;
constexpr const int RK_KEY_B						= 66;
constexpr const int RK_KEY_C						= 67;
constexpr const int RK_KEY_D						= 68;
constexpr const int RK_KEY_E						= 69;
constexpr const int RK_KEY_F						= 70;
constexpr const int RK_KEY_G						= 71;
constexpr const int RK_KEY_H						= 72;
constexpr const int RK_KEY_I						= 73;
constexpr const int RK_KEY_J						= 74;
constexpr const int RK_KEY_K						= 75;
constexpr const int RK_KEY_L						= 76;
constexpr const int RK_KEY_M						= 77;
constexpr const int RK_KEY_N						= 78;
constexpr const int RK_KEY_O						= 79;
constexpr const int RK_KEY_P						= 80;
constexpr const int RK_KEY_Q						= 81;
constexpr const int RK_KEY_R						= 82;
constexpr const int RK_KEY_S						= 83;
constexpr const int RK_KEY_T						= 84;
constexpr const int RK_KEY_U						= 85;
constexpr const int RK_KEY_V						= 86;
constexpr const int RK_KEY_W						= 87;
constexpr const int RK_KEY_X						= 88;
constexpr const int RK_KEY_Y						= 89;
constexpr const int RK_KEY_Z						= 90;
constexpr const int RK_KEY_LEFT_BRACKET				= 91; /* [ */
constexpr const int RK_KEY_BACKSLASH				= 92; /* \ */
constexpr const int RK_KEY_RIGHT_BRACKET			= 93; /* ] */
constexpr const int RK_KEY_GRAVE_ACCENT				= 96; /* ` */
constexpr const int RK_KEY_WORLD_1					= 161; /* non-US #1 */
constexpr const int RK_KEY_WORLD_2					= 162; /* non-US #2 */
constexpr const int RK_KEY_ESCAPE					= 256;
constexpr const int RK_KEY_ENTER					= 257;
constexpr const int RK_KEY_TAB						= 258;
constexpr const int RK_KEY_BACKSPACE				= 259;
constexpr const int RK_KEY_INSERT					= 260;
constexpr const int RK_KEY_DELETE					= 261;
constexpr const int RK_KEY_RIGHT					= 262;
constexpr const int RK_KEY_LEFT						= 263;
constexpr const int RK_KEY_DOWN						= 264;
constexpr const int RK_KEY_UP						= 265;
constexpr const int RK_KEY_PAGE_UP					= 266;
constexpr const int RK_KEY_PAGE_DOWN				= 267;
constexpr const int RK_KEY_HOME						= 268;
constexpr const int RK_KEY_END						= 269;
constexpr const int RK_KEY_CAPS_LOCK				= 280;
constexpr const int RK_KEY_SCROLL_LOCK				= 281;
constexpr const int RK_KEY_NUM_LOCK					= 282;
constexpr const int RK_KEY_PRINT_SCREEN				= 283;
constexpr const int RK_KEY_PAUSE					= 284;
constexpr const int RK_KEY_F1						= 290;
constexpr const int RK_KEY_F2						= 291;
constexpr const int RK_KEY_F3						= 292;
constexpr const int RK_KEY_F4						= 293;
constexpr const int RK_KEY_F5						= 294;
constexpr const int RK_KEY_F6						= 295;
constexpr const int RK_KEY_F7						= 296;
constexpr const int RK_KEY_F8						= 297;
constexpr const int RK_KEY_F9						= 298;
constexpr const int RK_KEY_F10						= 299;
constexpr const int RK_KEY_F11						= 300;
constexpr const int RK_KEY_F12						= 301;
constexpr const int RK_KEY_F13						= 302;
constexpr const int RK_KEY_F14						= 303;
constexpr const int RK_KEY_F15						= 304;
constexpr const int RK_KEY_F16						= 305;
constexpr const int RK_KEY_F17						= 306;
constexpr const int RK_KEY_F18						= 307;
constexpr const int RK_KEY_F19						= 308;
constexpr const int RK_KEY_F20						= 309;
constexpr const int RK_KEY_F21						= 310;
constexpr const int RK_KEY_F22						= 311;
constexpr const int RK_KEY_F23						= 312;
constexpr const int RK_KEY_F24						= 313;
constexpr const int RK_KEY_F25						= 314;
constexpr const int RK_KEY_KP_0						= 320;
constexpr const int RK_KEY_KP_1						= 321;
constexpr const int RK_KEY_KP_2						= 322;
constexpr const int RK_KEY_KP_3						= 323;
constexpr const int RK_KEY_KP_4						= 324;
constexpr const int RK_KEY_KP_5						= 325;
constexpr const int RK_KEY_KP_6						= 326;
constexpr const int RK_KEY_KP_7						= 327;
constexpr const int RK_KEY_KP_8						= 328;
constexpr const int RK_KEY_KP_9						= 329;
constexpr const int RK_KEY_KP_DECIMAL				= 330;
constexpr const int RK_KEY_KP_DIVIDE				= 331;
constexpr const int RK_KEY_KP_MULTIPLY				= 332;
constexpr const int RK_KEY_KP_SUBTRACT				= 333;
constexpr const int RK_KEY_KP_ADD					= 334;
constexpr const int RK_KEY_KP_ENTER					= 335;
constexpr const int RK_KEY_KP_EQUAL					= 336;
constexpr const int RK_KEY_LEFT_SHIFT				= 340;
constexpr const int RK_KEY_LEFT_CONTROL				= 341;
constexpr const int RK_KEY_LEFT_ALT					= 342;
constexpr const int RK_KEY_LEFT_SUPER				= 343;
constexpr const int RK_KEY_RIGHT_SHIFT				= 344;
constexpr const int RK_KEY_RIGHT_CONTROL			= 345;
constexpr const int RK_KEY_RIGHT_ALT				= 346;
constexpr const int RK_KEY_RIGHT_SUPER				= 347;
constexpr const int RK_KEY_MENU						= 348;
constexpr const int RK_KEY_LAST						= RK_KEY_MENU;

constexpr const int RK_MOUSE_BUTTON_0				= 0;
constexpr const int RK_MOUSE_BUTTON_1				= 1;
constexpr const int RK_MOUSE_BUTTON_2				= 2;
constexpr const int RK_MOUSE_BUTTON_3				= 3;
constexpr const int RK_MOUSE_BUTTON_4				= 4;
constexpr const int RK_MOUSE_BUTTON_5				= 5;
constexpr const int RK_MOUSE_BUTTON_6				= 6;
constexpr const int RK_MOUSE_BUTTON_7				= 7;
constexpr const int RK_MOUSE_BUTTON_LAST			= RK_MOUSE_BUTTON_7;
constexpr const int RK_MOUSE_BUTTON_LEFT			= RK_MOUSE_BUTTON_0;
constexpr const int RK_MOUSE_BUTTON_RIGHT			= RK_MOUSE_BUTTON_1;
constexpr const int RK_MOUSE_BUTTON_MIDDLE			= RK_MOUSE_BUTTON_2;

constexpr const int RK_JOYSTICK_DEVICE_1			= 0;
constexpr const int RK_JOYSTICK_DEVICE_2			= 1;
constexpr const int RK_JOYSTICK_DEVICE_3			= 2;
constexpr const int RK_JOYSTICK_DEVICE_4			= 3;
constexpr const int RK_JOYSTICK_DEVICE_5			= 4;
constexpr const int RK_JOYSTICK_DEVICE_6			= 5;
constexpr const int RK_JOYSTICK_DEVICE_7			= 6;
constexpr const int RK_JOYSTICK_DEVICE_8			= 7;
constexpr const int RK_JOYSTICK_DEVICE_9			= 8;
constexpr const int RK_JOYSTICK_DEVICE_10			= 9;
constexpr const int RK_JOYSTICK_DEVICE_11			= 10;
constexpr const int RK_JOYSTICK_DEVICE_12			= 11;
constexpr const int RK_JOYSTICK_DEVICE_13			= 12;
constexpr const int RK_JOYSTICK_DEVICE_14			= 13;
constexpr const int RK_JOYSTICK_DEVICE_15			= 14;
constexpr const int RK_JOYSTICK_DEVICE_16			= 15;
constexpr const int RK_JOYSTICK_DEVICE_FIRST		= RK_JOYSTICK_DEVICE_1;
constexpr const int RK_JOYSTICK_DEVICE_LAST			= RK_JOYSTICK_DEVICE_16;
constexpr const int RK_JOYSTICK_BUTTON_0			= 0;
constexpr const int RK_JOYSTICK_BUTTON_1			= 1;
constexpr const int RK_JOYSTICK_BUTTON_2			= 2;
constexpr const int RK_JOYSTICK_BUTTON_3			= 3;
constexpr const int RK_JOYSTICK_BUTTON_4			= 4;
constexpr const int RK_JOYSTICK_BUTTON_5			= 5;
constexpr const int RK_JOYSTICK_BUTTON_6			= 6;
constexpr const int RK_JOYSTICK_BUTTON_7			= 7;
constexpr const int RK_JOYSTICK_BUTTON_8			= 8;
constexpr const int RK_JOYSTICK_BUTTON_9			= 9;
constexpr const int RK_JOYSTICK_AXIS_0			    = 0;
constexpr const int RK_JOYSTICK_AXIS_1			    = 1;
constexpr const int RK_JOYSTICK_AXIS_2			    = 2;
constexpr const int RK_JOYSTICK_AXIS_3			    = 3;
constexpr const int RK_JOYSTICK_AXIS_4			    = 4;
constexpr const int RK_JOYSTICK_AXIS_5			    = 5;
constexpr const int RK_JOYSTICK_AXIS_6			    = 6;
constexpr const int RK_JOYSTICK_AXIS_7			    = 7;

constexpr const int RK_GAMEPAD_BUTTON_A			    = 0;
constexpr const int RK_GAMEPAD_BUTTON_B			    = 1;
constexpr const int RK_GAMEPAD_BUTTON_X			    = 2;
constexpr const int RK_GAMEPAD_BUTTON_Y			    = 3;
constexpr const int RK_GAMEPAD_AXIS_LEFT_X	        = 0;
constexpr const int RK_GAMEPAD_AXIS_LEFT_Y	        = 1;
constexpr const int RK_GAMEPAD_AXIS_RIGHT_X	        = 2;
constexpr const int RK_GAMEPAD_AXIS_RIGHT_Y	        = 3;
constexpr const int RK_GAMEPAD_AXIS_LEFT_TRIGGER    = 4;
constexpr const int RK_GAMEPAD_AXIS_RIGHT_TRIGGER   = 5;